### ISSUE TITLE
Unable to resolve action `dosymep/vk-teams-action@v1`

### ISSUE THREAD

**Issue by pavel-filimonov** [dosymep/vk-teams-action#1]
I'm trying to use this action, but calling this action ends with this error:
`Unable to resolve action dosymep/vk-teams-action@v1, unable to find version v1`

Is it supporting now?

**Comment by dosymep** [comment]
Yes, it's work for me, but I write version `v1.0.0`
Working example https://github.com/Bim4Everyone/Bim4EveryoneSetup/blob/master/.github/workflows/notification.yml#L36
